### ISSUE TITLE
Request for example with JPAcacheLoader and JpaCacheStore

### ISSUE THREAD

**Issue by viju2008** [thegridman/coherence-k8s-example#4]
Please provide us an example of spring-boot-example-storage with JPACacheLoader  JpaCacheStore and entity JPA for Custom image to database table mapping. We are not using TopLink

Can both the Jcache and JPAcacheloader mixed in the same example.

Have messaged you in slack the requirement.

This example as i understood use Jcache. Please correct me if i am wrong as i am new to coherence

**Comment by viju2008** [comment]
I found one example of it here bit couldnt understand how to use it in our example

https://github.com/coherence-community/coherence-demo/blob/master/src/main/java/com/oracle/coherence/demo/cachestore/JpaCacheLoader.java

**Comment by thegridman** [comment]
Do not use the JPA CacheStore, you are using Spring Boot and it is simple to write a Spring Boot JPA CacheStore like in this example project. The Coherence Demo example you linked to above will not integrate very well with Spring Boot.
